AWSTemplateFormatVersion: 2010-09-09
Description: Security Group to connect to Aurora cluster from on-prem Jump Server
Resources:
  rSecurityGroupEIPTeam:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow access to on-prem Jump Server
      GroupName: "Test"
      VpcId: "vpc-f1442589"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 40.192.0.0/10
      Tags:
        - Key: Restricted
          Value: Restricted